### ISSUE TITLE
data-live demo got "ZeroDivisionError: float division by zero"

### ISSUE THREAD

**Issue by huuquynh** [happydasch/btplotting#2]
I tried to use live demo (both 2 samples), and it runs for a short while (2-3 minutes), then this error happens.

I don't think that this error is from indicators, but the debug message looks like relatived indicator issues. I wonder because the sample runs with mature indicators, not a new one.

`Traceback (most recent call last):
  File "/home/bt-learning/data-live.py", line 101, in <module>
    cerebro, strat = _run_resampler(data_timeframe=bt.TimeFrame.Ticks,
  File "/home/bt-learning/data-live.py", line 94, in _run_resampler
    res = cerebro.run()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/cerebro.py", line 1630, in _runnext
    strat._next()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/strategy.py", line 347, in _next
    super(Strategy, self)._next()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/lineiterator.py", line 263, in _next
    indicator._next()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/lineiterator.py", line 263, in _next
    indicator._next()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/linebuffer.py", line 621, in _next
    self.nextstart()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/lineroot.py", line 144, in nextstart
    self.next()
  File "/home/bt-learning/venv/lib/python3.8/site-packages/backtrader/linebuffer.py", line 744, in next
    self[0] = self.operation(self.a[0], self.b[0])`

Or is there any misunderstood here?

Thank you very much!

**Comment by happydasch** [comment]
this is mostly an issue of the fakefeed implementation. i won't fix this, since it is taken from backtrader_plotting, but feel free to open issues regarding btplotting directly. sorry for this.
