### ISSUE TITLE
BacktraderPlottingOptBrowser doesn't work

### ISSUE THREAD

**Issue by FlamesAndTears** [happydasch/btplotting#24]
Running the simple example from the deoms (`demos/optimization.py`, just changes the port), produces the following error:
```
Open browser at: http://localhost:8087
ERROR:tornado.application:Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8087', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\bokeh\server\views\doc_handler.py", line 52, in get
    session = await self.get_session()
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\bokeh\server\views\session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\bokeh\server\contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\bokeh\application\application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\bokeh\application\handlers\function.py", line 132, in modify_document
    self._func(doc)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\webapp.py", line 49, in make_document
    model = self._model_factory_fnc(doc)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\optbrowser.py", line 113, in build_optresult_model
    [selector, _get_model(selector_cds, 0)],
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\optbrowser.py", line 99, in _get_model
    self._optresults[selected][0])
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\app.py", line 543, in plot_optmodel
    return self.generate_model(0)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\app.py", line 357, in generate_model
    panels.append(tab.get_panel())
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tab.py", line 35, in get_panel
    child, title = self._get_panel()
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tabs\metadata.py", line 138, in _get_panel
    self.content = self._create_content()
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tabs\metadata.py", line 132, in _create_content
    [self._get_metadata_info()]
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tabs\metadata.py", line 105, in _get_metadata_info
    acolumns = self._get_metadata_columns(self._figurepage.strategy)
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tabs\metadata.py", line 99, in _get_metadata_columns
    acolumns.extend(self._get_strategy(strategy))
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\tabs\metadata.py", line 50, in _get_strategy
    childs.append(self._get_title(f'Strategy: {obj2label(strategy)}'))
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\btplotting\helper\label.py", line 25, in obj2label
    raise RuntimeError(f'Unsupported type: {obj.__class__}')
RuntimeError: Unsupported type: <class 'NoneType'>
ERROR:tornado.access:500 GET / (::1) 171.54ms
```

When trying to set `optreturn=False` I get:
```
ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://localhost:8081';                       use --allow-websocket-origin=localhost:8081 or set BOKEH_ALLOW_WS_ORIGIN=localhost:8081 to permit this; currently we allow origins {'localhost:80'}
WARNING:tornado.access:403 GET /ws (::1) 1.00ms
```

**Comment by iniself** [comment]
```
server = Server(apps, port=port, allow_websocket_origin=[address], io_loop=ioloop)
```

btplotting/webapp.py file : `allow_ websocket_ origin=[address]` is wrong. 
in the code, `address` is default `localhost`, so  no matter what you do, the `bokeh.settings.settings.allowed_ws_origin` is always `localhost:80`

you can fix it by yourself

**Comment by happydasch** [comment]
thanks for reporting, fixed in latest commit
