### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by ArmanBM** [happydasch/btplotting#26]
I keep getting this error. "500: Internal Server Error"

I have done installing btplotting and calling it using:
cerebro.addanalyzer(BacktraderPlottingLive, address="*", port=7692)
I've also tried different port numbers
also googling didnt help.

**Comment by ArmanBM** [comment]
> I keep getting this error. "500: Internal Server Error"
> 
> I have done installing btplotting and calling it using: cerebro.addanalyzer(BacktraderPlottingLive, address="*", port=7692) I've also tried different port numbers also googling didnt help.

This is The Error I get when running the script (In VSCode Terminal):

`Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:7691', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\Arman\anaconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Users\Arman\anaconda3\lib\site-packages\bokeh\server\views\doc_handler.py", line 52, in get
    session = await self.get_session()
  File "C:\Users\Arman\anaconda3\lib\site-packages\bokeh\server\views\session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\Arman\anaconda3\lib\site-packages\bokeh\server\contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\Arman\anaconda3\lib\site-packages\bokeh\application\application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "C:\Users\Arman\anaconda3\lib\site-packages\bokeh\application\handlers\function.py", line 132, in modify_document
    self._func(doc)
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\webapp.py", line 49, in make_document
    model = self._model_factory_fnc(doc)
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\analyzers\plot.py", line 62, in _app_cb_build_root_model
    client = LiveClient(doc,
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\live\client.py", line 53, in __init__
    self.updatemodel()
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\live\client.py", line 169, in updatemodel
    panels.append(tab.get_panel())
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\tab.py", line 35, in get_panel
    child, title = self._get_panel()
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\tabs\source.py", line 25, in _get_panel
    Div(text=self._getSource(),
  File "C:\Users\Arman\anaconda3\lib\site-packages\btplotting\tabs\source.py", line 15, in _getSource
    text = inspect.getsource(
  File "C:\Users\Arman\anaconda3\lib\inspect.py", line 985, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\Arman\anaconda3\lib\inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\Arman\anaconda3\lib\inspect.py", line 780, in findsource
    file = getsourcefile(object)
  File "C:\Users\Arman\anaconda3\lib\inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "C:\Users\Arman\anaconda3\lib\inspect.py", line 665, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: <class '__main__.SmaCross'> is a built-in class`

**Comment by happydasch** [comment]
its due to the source code view. you will need to disable it.

try something like this:
```
from btplotting import BacktraderPlotting
from btplotting.tabs import AnalyzerTab, MetadataTab, LogTab

p = BacktraderPlotting(use_default_tabs=False, tabs=[AnalyzerTab, MetadataTab, LogTab])
cerebro.plot(p)

```

**Comment by happydasch** [comment]
for live plotting it would be something like:

```
from btplotting import BacktraderPlottingLive
from btplotting.tabs import AnalyzerTab, MetadataTab, LogTab

cerebro.addanalyzer(BacktraderPlottingLive, use_default_tabs=False, tabs=[AnalyzerTab, MetadataTab, LogTab])
```

**Comment by ArmanBM** [comment]
Thanks a MILLION times ♥
You Saved my day.
Problem FIXED :)
