### ISSUE TITLE
Unable to run at all

### ISSUE THREAD

**Issue by Onepamopa** [happydasch/btplotting#3]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from btplotting import BacktraderPlotting
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting/__init__.py", line 2, in <module>
    from .analyzers import LivePlotAnalyzer as BacktraderPlottingLive
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting/analyzers/__init__.py", line 1, in <module>
    from .plot import LivePlotAnalyzer
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting/analyzers/plot.py", line 13, in <module>
    from ..live.client import LiveClient
ModuleNotFoundError: No module named 'btplotting.live'

**Comment by happydasch** [comment]
Thanks for pointing this out

**Comment by Onepamopa** [comment]
This was caused due to backtrader_plotting being installed / enabled in the imports, which was my mistake.
