### ISSUE TITLE
Please check the requirement packages

### ISSUE THREAD

**Issue by huuquynh** [happydasch/btplotting#35]
Hi @happydasch ,

After make a fresh install computer. I got the error when plotting live, and stuck in find what is wrong. The plotting live got the error on browser console:
```
[bokeh]: could not set init ranges
```

and result is nothing plotting at all.

It throws an exception also:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hq/.venv/lib/python3.8/site-packages/btplotting/live/datahandler.py", line 217, in _t_thread
    data = self._app.generate_data(
  File "/home/hq/.venv/lib/python3.8/site-packages/btplotting/app.py", line 451, in generate_data
    clock_values[smallest] = generator.get_clock(
  File "/home/hq/.venv/lib/python3.8/site-packages/btplotting/clock.py", line 91, in get_clock
    arr = get_slice_with_end(arr, start, end)
  File "/home/hq/.venv/lib/python3.8/site-packages/btplotting/clock.py", line 14, in get_slice_with_end
    slice = list(data)[start:end] + [data[end]]
TypeError: slice indices must be integers or None or have an __index__ method
```

The steps to make install as:
1. Install backtrader
2. Install btplotting
3. Install another packages: websockets, TA-Lib, requests, schedule, ujson

Here is my pip freeze:

```
backtrader==1.9.76.123
bokeh==2.4.3
btplotting @ git+https://github.com/happydasch/btplotting@512780f8ab71395fef3667e872deca3a8a2f2e9a
certifi==2022.6.15
charset-normalizer==2.1.0
cycler==0.11.0
fonttools==4.33.3
idna==3.3
Jinja2==3.1.2
kiwisolver==1.4.3
MarkupSafe==2.1.1
matplotlib==3.5.2
numpy==1.23.0
packaging==21.3
pandas==1.4.3
Pillow==9.2.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
requests==2.28.1
schedule==1.1.0
six==1.16.0
TA-Lib==0.4.24
tornado==6.2
typing_extensions==4.3.0
ujson==5.4.0
urllib3==1.26.9
websockets==10.3
```

**Comment by huuquynh** [comment]
But plotting on backtest is OK. Only got nothing on plotting live-view.

**Comment by huuquynh** [comment]
This is the error from browser console: with bokeh==2.3.3
![image](https://user-images.githubusercontent.com/145587/177245245-c3926e5e-e7cb-420d-b7cd-7a0fde41c1d1.png)

**Comment by huuquynh** [comment]
The issue is not from bokeh at all. I tried to rollback to previous version, and run well with pandas 1.3.5.

**Comment by huuquynh** [comment]
I feel OK with pandas 1.3.5 and bokeh 2.3.3
