### ISSUE TITLE
Missing file, unable to run

### ISSUE THREAD

**Issue by Onepamopa** [happydasch/btplotting#4]
Actually, the whole folder "templates" is missing.

Traceback (most recent call last):
  File "main.py", line 494, in <module>
    start_test()
  File "main.py", line 470, in start_test
    cerebro.plot(p)
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/backtrader/cerebro.py", line 989, in plot
    rfig = plotter.plot(strat, figid=si * 100,
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/app.py", line 563, in plot
    self.create_figurepage(
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/app.py", line 319, in create_figurepage
    self._blueprint_strategy(figid, filter)
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/app.py", line 203, in _blueprint_strategy
    figure = Figure(
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/figure.py", line 245, in __init__
    self._init_figure()
  File "/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/figure.py", line 335, in _init_figure
    formatter_code = pkgutil.get_data(
  File "/usr/lib/python3.8/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/templates/js/tick_formatter.js'

**Comment by happydasch** [comment]
should be fixed, please close if it works.

**Comment by Onepamopa** [comment]
Still getting the exact same error

**Comment by happydasch** [comment]
i see, will need to test it out with python 3.8

**Comment by Onepamopa** [comment]
$ ls /home/user/PycharmProjects/backtrader/venv/lib/python3.8/site-packages/btplotting-0.1.0-py3.8.egg/btplotting/templates/js/
__init__.py  __pycache__

**Comment by happydasch** [comment]
for now, just download the repository and copy the btplotting folder into your project dir. it seems, its because of the installation script.

**Comment by Onepamopa** [comment]
Yeah, already did that - no errors (so far).

**Comment by happydasch** [comment]
should work now :)
