### ISSUE TITLE
ValueError: 'id' cannot be used together with property initializers  in Live plotting.

### ISSUE THREAD

**Issue by zgpnuaa** [happydasch/btplotting#51]
```
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8065', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "D:\VScodeProjects\dangu\venv_310\lib\site-packages\btplotting\analyzers\plot.py", line 64, in _app_cb_build_root_model   
    client = LiveClient(doc,
  File "D:\VScodeProjects\dangu\venv_310\lib\site-packages\btplotting\live\client.py", line 55, in __init__
    self.model, self._refresh_fnc = self._createmodel()
  File "D:\VScodeProjects\dangu\venv_310\lib\site-packages\btplotting\live\client.py", line 177, in _createmodel
    tabs = Tabs(
  File "D:\VScodeProjects\dangu\venv_310\lib\site-packages\bokeh\model\model.py", line 97, in __new__
    raise ValueError("'id' cannot be used together with property initializers")
ValueError: 'id' cannot be used together with property initializers
500 GET / (::1) 150.34ms
```

**Comment by happydasch** [comment]
will close this in favor of #46
