### ISSUE TITLE
report error when I run `https://github.com/happydasch/btplotting/blob/master/demos/optimization.py` 

### ISSUE THREAD

**Issue by 8debug** [happydasch/btplotting#62]
report error when I run `https://github.com/happydasch/btplotting/blob/master/demos/optimization.py` 

```
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
C:\Python311\Lib\site-packages\btplotting\clock.py:316: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[name] = df[name].fillna(method='ffill')
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:81', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\bokeh\server\views\session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\bokeh\server\contexts.py", line 240, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Python311\Lib\site-packages\bokeh\application\application.py", line 190, in initialize_document
    h.modify_document(doc)
  File "C:\Python311\Lib\site-packages\bokeh\application\handlers\function.py", line 140, in modify_document
    self._func(doc)
  File "C:\Python311\Lib\site-packages\btplotting\webapp.py", line 54, in make_document
    model = self._model_factory_fnc(doc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\btplotting\optbrowser.py", line 130, in build_optresult_model
    [selector, _get_model(selector_cds, 0)],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\btplotting\optbrowser.py", line 103, in _get_model
    return self._app.plot_optmodel(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\btplotting\app.py", line 511, in plot_optmodel
    return self.generate_bokeh_model(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\btplotting\app.py", line 343, in generate_bokeh_model
    tab_panels = self.generate_bokeh_model_tab_panels()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\btplotting\app.py", line 413, in generate_bokeh_model_tab_panels
    g = gridplot(plot_figures,
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\bokeh\layouts.py", line 333, in gridplot
    toolbar = Toolbar(
              ^^^^^^^^
TypeError: bokeh.models.tools.Toolbar() got multiple values for keyword argument 'logo'
500 GET / (::1) 715.09ms

```

**Comment by 8debug** [comment]
Python 3.11

**Comment by 8debug** [comment]
解决了
