### ISSUE TITLE
'DivByZero' object has no attribute 'size'

### ISSUE THREAD

**Issue by 349286991** [happydasch/btplotting#8]
我自定义了一个指标 
 # VAR1 / VAR2
        dpv = bt.DivByZero(self.data.pd1, self.data.pd2, 999999999)
        self.data.dpv = dpv
使用如上方式计算
当我启动时会报如下错误：
Traceback (most recent call last):
  File "D:/pythonProject/test/ztbQuant.py", line 183, in <module>
    cerebro.plot(bh)
  File "C:\Users\being\anaconda3\lib\site-packages\backtrader\cerebro.py", line 989, in plot
    rfig = plotter.plot(strat, figid=si * 100,
  File "C:\Users\being\anaconda3\lib\site-packages\backtrader_plotting\bokeh\bokeh.py", line 511, in plot
    df: pd.DataFrame = self.build_strategy_data(obj, start, end)
  File "C:\Users\being\anaconda3\lib\site-packages\backtrader_plotting\bokeh\bokeh.py", line 473, in build_strategy_data
    for lineidx in range(obj.size()):
AttributeError: 'DivByZero' object has no attribute 'size'

**Comment by happydasch** [comment]
this is another plotting lib for backtrader. You are using backtrader_plotting (https://github.com/verybadsoldier/backtrader_plotting). Try btplotting (https://github.com/happydasch/btplotting) to see if the issue is still there.
